ALTER TABLE "tickers" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "tickers" ADD COLUMN IF NOT EXISTS "weburl" TEXT;
ALTER TABLE "tickers" ADD COLUMN IF NOT EXISTS "logo" TEXT;
ALTER TABLE "tickers" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "tickers" ADD COLUMN IF NOT EXISTS "ipo" TIMESTAMP(3);
ALTER TABLE "tickers" ADD COLUMN IF NOT EXISTS "country" TEXT;
